# Generated by Django 2.2.4 on 2023-04-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_sight_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='previous',
        ),
        migrations.AddField(
            model_name='sight',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sight',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='sights.Sight'),
        ),
    ]
